[package]
name = "screencap"
version = "0.1.0"
authors = ["Curtis Millar <curtis@curtism.me>"]
edition = "2018"
description = """\
	Uses ffmpeg and gnome-screenshot to capture screen or region.
"""

[dependencies]
clap = "2.32.0"
chrono = "0.4.6"
hostname = "0.1.5"
num_cpus = "1.9.0"
